# These are supported funding model platforms

- github: #sgoggins 
- tidelift: # Replace with a single Tidelift platform-name/package-name e.g., angrynarwhal/lottery
- community_bridge: # Replace with a single Community Bridge project-name e.g., angrynarwhal/lottery
- lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., angrynarwhal/lottery
